mkgif/urls.py
from django.urls import path
from . import views

app_name = "mkgif"

urlpatterns = [
    path("", views.index, name="index"),
    path("details/<int:pk>", views.details, name="details"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mkgif.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mkgif/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
import django_rq
from .utils import mk_gif_ffmpeg
import os


class Animation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def enqueue(self, params):
        django_rq.enqueue(
            mk_gif_ffmpeg,
            job_id=f"{self.pk}",
            kwargs={
                "pk": self.pk,
                "params": params,
            },
        )

    @property
    def worker_is_done(self):
        output_exists = os.path.exists(f"media/{self.pk}/out.gif")
        queue = django_rq.get_queue("default")
        job = queue.fetch_job(f"{self.pk}")
        result = job.result if job else None

        if result and output_exists:
            return True
        elif output_exists and job == None:
            return True
        else:
            return False


class Image(models.Model):
    def image_path(self, filename):
        return f"{self.animation.pk}/{filename}"

    animation = models.ForeignKey("Animation", on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_path)

mkgif/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponsePermanentRedirect
from .models import Animation, Image
import django_rq
from rq.job import Job


@login_required
def index(request):
    if request.method == "POST":
        anim = Animation.objects.create(name=request.POST["name"], user=request.user)
        for img in request.FILES.getlist("imgs"):
            Image.objects.create(animation=anim, image=img)
        anim.enqueue({})

    anims = Animation.objects.all()
    context = {"anims": anims}
    return render(request, "mkgif/index.html", context)


@login_required
def details(request, pk):
    anim = get_object_or_404(Animation, pk=pk)

    images = Image.objects.filter(animation=pk)
    context = {"anim": anim, "images": images}
    if request.method == "GET":
        if anim.user == request.user:
            context["is_my_anim"] = True

    elif request.method == "DELETE":
        if anim.user == request.user:
            anim.delete()
            images.delete()
            return redirect("mkgif:index")
        else:
            raise PermissionDenied("This animation does not belong to you!")

    return render(request, "mkgif/details.html", context)

mkgif/templates/mkgif/details.html
{% extends 'mkgif/partials/base.html' %}
{% block content %}
  <div class="animation">
    <h1>Animation: <u>{{ anim.name }}</u></h1>
    {% if anim.worker_is_done == True %}
    {% load static %}
    {% get_media_prefix as MEDIA_PREFIX %}
    <img src="{{ MEDIA_PREFIX }}{{ anim.pk }}/out.gif" alt="animation">
    {% else %}
    <p>Animation is still being created</p>
    {% endif %}
  </div>
  {% include 'mkgif/partials/details-controls.html' %}
{% endblock %}

mkgif/templates/mkgif/index.html
{% extends 'mkgif/partials/base.html' %}

{% block content %}
            <p>My GIF Animations:</p>
            <table>
                {% for anim in anims %}
                <tr>
                <td>{{ anim.pk }}</td>
                <td><a href="{% url 'mkgif:details' anim.pk %}">{{ anim.name }}</a></td>
                </tr>
                {% endfor %}
            </table>
            <hr>
            <form action="{% url 'mkgif:index' %}" method="POST" enctype="multipart/form-data">
                <fieldset>
                    <legend><label>Add New GIF Animation</label></legend>
                    {% csrf_token %}
                    <input name="name" type="text" placeholder="Animation name">
                    <input name="imgs" type="file" multiple>
                    <button>Submit</button>
                </fieldset>
            </form>
{% endblock %}

mkgif/templates/mkgif/partials/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/holiday.css@0.9.8" />
        {% load static %}
        <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
        <script src="https://unpkg.com/htmx.org@1.9.3" integrity="sha384-lVb3Rd/Ca0AxaoZg5sACe8FJKF0tnUgR2Kd7ehUOG5GCcROv5uBIZsOqovBAcWua" crossorigin="anonymous"></script>
        <title>Make GIF</title>
    </head>
    <body>
        <header>
            <h1>Make GIF Animations</h1>
        </header>
        <nav>
            <ul>
                <li><a href="{% url 'mkgif:index' %}">Home</a></li>
                <li>
                    <span>{{ user }}</span>
                    <ul>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                    </span>
                </li>
            </ul>
        </nav>
        <main>
          {% block content %}

          {% endblock %}
        </main>
      <script defer>
          document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
          })
      </script>
    </body>
</html>

mkgif/templates/mkgif/partials/details-controls.html
{% if is_my_anim == True %}
  <div class="anim-controls">

    <button 
      class="delete-btn"
      hx-delete="{% url 'mkgif:details' anim.pk %}"
      hx-trigger="click"
      hx-target="body"
    >Delete</button>
  </div>
{% endif %}